% species in VerhKooy2025_SI that are not in AmP
nm = { ...
 % Amphibia
'Discoglossus_pictus'
'Rhinella_marina'
'Anaxyrus_cognatus'
'Colostethus_inguinalis'
'Dendrobates_auratus'
'Colostethus_nubicola'
'Pseudacris_crucifer'
'Pseudacris_regilla'
'Osteopilus_septentrionalis'
'Agalychnis_callidryas'
'Smilisca_fodiens'
'Hyla_cinerea'
'Hyla_arenicolor'
'Hyla_chrysoscelis'
'Hyla_gratiosa'
'Hyla_squirella'
'Hyla_versicolor'
'Semnodactylus_wealii'
'Kassina_senegalensis'
'Gastrophryne_carolinensis'
'Kaloula_pulchra'
'Rana_pipiens'
'Lithobates_catesbeiana'
'Lithobates_sylvaticus'
'Spea_hammondii'
'Ambystoma_gracile'
'Ambystoma_jeffersonianum'
'Ambystoma_tigrinum'
'Amphiuma_tridactylum'
'Pseudoeurycea_bellii'
'Aneides_lugubris'
'Bolitoglossa_occidentalis'
'Gyrinophilus_porphyriticus'
'Pseudoeurycea_gadovii'
'Pseudoeurycea_smithi'
'Pseudotriton_ruber'
'Geotrypetes_seraphini'
% squamata
'Ophisaurus_ventralis'
'Anniella_pulchra'
'Pituophis_catenifer'
'Ctenosaura_similis'
'Sauromalus_hispidus'
'Tupinambis_nigropunctatus'
'Trogonophis_wiegmanni'
'Varanus_rosenbergi'
'Varanus_rosenbergi'
'Varanus_gouldii'
'Varanus_panoptes'
'Varanus_mertensi'
'Varanus_acanthurus'
'Varanus_brevicauda'
'Varanus_caudolineatus'
'Varanus_eremius'
'Varanus_salvator'
'Mabuya_capensis'
'Mabuya_varia'
'Mabuya_sulcata'
'Scelotes_gronovii'
'Acontias_meleagris'
'Typhlacontias_brevipes'
% Aves
'Myrmotherula_fulviventris'
'Sclerurus_guatemalensis'
'Pipra_mentalis' % Ceratopipra_mentalis
'Oncostoma_olivaceum'
'Elaenia_chiriquensis'
'Tyrannulus_elatus'
'Rhynchocyclus_olivaceus'
'Capsiempis_flaveola'
'Tolmomyias_assimillis'
'Ramphocaenus_melanurus'
'Ramphocelus_dimidiatus'
'Ramphocelus_dimidiatus'
'Thryothorus_fasciatoventris'
'Thryothorus_leucotis'
'Thryothorus_leucotis'
'Thryothorus_rutilus'
'Turdus_grayi'
'Turdus_grayi'
'Vireo_flavoviridis'
'Vireo_flavoviridis'
'Hylophilus_flavipes'
'Euphonia_laniirostris'
'Euphonia_laniirostris'
'Cyanocompsa_cyanoides'
'Cyanocompsa_cyanoides'
'Habia_fuscicauda'
'Phrygilus_gayi'
'Oryzoborus_angolensis'
'Saltator_striatipectus'
'Sporophila_nigricollis'
'Thraupis_palmarum'
'Arremonops_conirostris'
'Arremonops_conirostris'
'Basileuterus_rufifrons'
% Mammalia
'Helogale_parvula'
'Mungos_mungo'
'Nesotragus_moschatus' % Neotragus moschatus
'Gazella_granti'
'Microcavia_niata'
'Abrothrix_andinus'
'Abrothrix_andinus'
'Abrothrix_andinus'
'Abrothrix_andinus'
'Abrothrix_andinus'
'Abrothrix_longipilis'
'Abrothrix_olivaceus'
'Abrothrix_lanosus'
'Akodon_albiventer'
'Auliscomys_boliviensis'
'Graomys_griseoflavus'
'Oryzomys_longicaudatus' % Oligoryzomys longicaudatus
'Reithrodon_auritus'
'Perognathus_fallax' % Chaetodipus fallax
'Perognathus_fallax' % Chaetodipus fallax
'Perognathus_fallax' % Chaetodipus fallax
'Octodon_bridgesi'   % Octodon bridgesii 
'Octodon_lunatus'
'Rattus_colletti'
'Rattus_villosissimus'
};
