
    close all
    clear all
    
    shstat_options('default');
    shstat_options('y_transform', 'log10');
    shstat_options('x_transform', 'none');
    vars = read_allStat('E_Hb', 'L_b', 'kap'); 
    EHLb = vars(:,1) ./ vars(:,2).^3; kap = vars(:,3); 
    ytxt = '_{10}log [E_H^b], J/cm^3';
    xtxt = '\kappa, -';
    v1 = kap; v2 = EHLb; vtxt = 'kap_EHLb';

    figure(1)
    legend_RXSE = {...
        {'o', 8, 3, [1 0 0], [1 0 0]}, 'Echinodermata'; ....
        {'o', 8, 3, [0 0 0], [0 0 0]}, 'Radiata'; ...
        {'o', 8, 3, [0 0 0], [0 0 1]}, 'Xenacoelomorpha'; ...
        {'o', 8, 3, [0 0 1], [0 0 1]}, 'Spiralia'; ...
        {'o', 8, 3, [1 0 1], [1 0 1]}, 'Ecdysozoa'; ....
    };
    [Hfig Hleg] = shstat([v1, v2], legend_RXSE, 'invertebrates', 1); 
    figure(Hfig)
    xlabel(xtxt)      
    ylabel(ytxt)
    %saveas(gca,[vtxt, '_RXSE.png'])
    %saveas(Hleg,['legend_', vtxt, '_RXSE.png'])
    
    figure(3)
    legend_fish = {...
        {'o', 8, 3, [0 0 0], [0 0 0]}, 'Agnatha'; ...
        {'o', 8, 3, [1 0 0], [1 0 0]}, 'Chondrichthyes'; ...
        {'o', 8, 3, [1 0 1], [0 0 1]}, 'Latimeria'; ....
        {'o', 8, 3, [1 0 1], [1 0 0]}, 'Dipnoi'; ....
        {'o', 8, 3, [1 0 1], [1 0 1]}, 'Amphibia'; ....
        {'o', 8, 3, [0 0 1], [0 0 1]}, 'Actinopterygii'; ...
    };
    [Hfig Hleg] = shstat([v1, v2], legend_fish, 'fish & amphibia', 3); 
    figure(Hfig)
    kap = linspace(2e-3,1-4e-4,200); 
    plot(kap, log10((1 - kap)./ kap * 5230), 'k', 'LineWidth', 3)
    xlabel(xtxt)      
    ylabel(ytxt)
    saveas(gca,[vtxt, '_fish.png'])
    saveas(Hleg,['legend_', vtxt, '_fish.png'])

    figure(5)
    legend_aves = {...
        {'o', 8, 3, [0 0 0], [0 0 0]}, 'Lepidosauria'; ....
        {'o', 8, 3, [1 0 0], [1 0 0]}, 'Aves'; ....
        {'o', 8, 3, [0 0 1], [0 0 1]}, 'Testudines'; ....
        {'o', 8, 3, [1 0 1], [0 0 1]}, 'Crocodilia'; ....
        {'o', 8, 3, [1 0 1], [1 0 1]}, 'Avemetatarsalia'; ....
    };
    [Hfig Hleg] = shstat([v1, v2], legend_aves, 'sauropsids', 5); 
    figure(Hfig) 
    figure(Hfig)
    xlabel(xtxt)      
    ylabel(ytxt)
    %saveas(gca,[vtxt, '_aves.png'])
    %saveas(Hleg,['legend_', vtxt, '_aves.png'])

    figure(7)
    legend_mamm = {...
       {'o', 8, 3, [0 0 0], [0 0 0]}, 'Prototheria'; ...  
       {'o', 8, 3, [0 0 1], [0 0 0]}, 'Marsupialia'; ...
       {'o', 8, 3, [0 0 1], [0 0 1]}, 'Xenarthra'; ...
       {'o', 8, 3, [0 0 1], [1 0 1]}, 'Afrotheria'; ....
       {'o', 8, 3, [0 0 1], [1 0 0]}, 'Laurasiatheria'; ....
       {'o', 8, 3, [1 0 1], [1 0 1]}, 'Gliriformes'; ....
       {'o', 8, 3, [1 0 1], [1 0 0]}, 'Scandentia'; ....
       {'o', 8, 3, [1 0 0], [1 0 0]}, 'Dermoptera'; ....
       {'o', 8, 3, [1 0 0], [1 .5 .5]}, 'Primates'; ....
    };
    [Hfig Hleg] = shstat([v1, v2], legend_mamm, 'mammals', 7); 
    figure(Hfig)
    xlabel(xtxt)      
    ylabel(ytxt)
    %saveas(gca,[vtxt, '_mamm.png'])
    %saveas(Hleg,['legend_', vtxt, '_mamm.png'])

