
    close all
    clear all
    
    shstat_options('default');
    shstat_options('x_transform', 'log10');
    shstat_options('y_transform', 'none');
    vars = read_allStat('s_M', 'p_Am', 'v', 'p_M', 'kap', 'L_i', 'E_m'); 
    p_Am = prod(vars(:,[1 2]),2); v = prod(vars(:,[1 3]),2); p_M = vars(:,4); kap = vars(:,5); L_i = vars(:,6); E_m = vars(:,7);
    xtxt = '_{10}log L_\infty, cm';
    ytxt = '_{10}log \kappa, -';
    v1 = L_i; v2 = kap; vtxt = 'Li_kap';

    figure(1)
    legend_RXSE = {...
        {'o', 8, 3, [1 0 0], [1 0 0]}, 'Echinodermata'; ....
        {'o', 8, 3, [0 0 0], [0 0 0]}, 'Radiata'; ...
        {'o', 8, 3, [0 0 0], [0 0 1]}, 'Xenacoelomorpha'; ...
        {'o', 8, 3, [0 0 1], [0 0 1]}, 'Spiralia'; ...
        {'o', 8, 3, [1 0 1], [1 0 1]}, 'Ecdysozoa'; ....
    };
    [Hfig Hleg] = shstat([v1, v2], legend_RXSE, 'invertebrates', 1); 
    figure(Hfig)
    xlabel(xtxt)      
    ylabel(ytxt)
    %saveas(gca,[vtxt, '_RXSE.png'])
    %saveas(Hleg,['legend_', vtxt, '_RXSE.png'])
    
    figure(3)
    legend_fish = {...
        {'o', 8, 3, [0 0 0], [0 0 0]}, 'Agnatha'; ...
        {'o', 8, 3, [1 0 0], [1 0 0]}, 'Chondrichthyes'; ...
        {'o', 8, 3, [0 0 1], [0 0 1]}, 'Actinopterygii'; ...
        {'o', 8, 3, [1 0 1], [0 0 1]}, 'Latimeria'; ....
        {'o', 8, 3, [1 0 1], [1 0 0]}, 'Dipnoi'; ....
        {'o', 8, 3, [1 0 1], [1 0 1]}, 'Amphibia'; ....
    };
    [Hfig Hleg] = shstat([v1, v2], legend_fish, 'fish & amphibia', 3); 
    figure(Hfig)
    xlabel(xtxt)      
    ylabel(ytxt)
    %saveas(gca,[vtxt, '_fish.png'])
    %saveas(Hleg,['legend_', vtxt, '_fish.png'])

    figure(5)
    legend_aves = {...
        {'o', 8, 3, [0 0 0], [0 0 0]}, 'Lepidosauria'; ....
        {'o', 8, 3, [1 0 0], [1 0 0]}, 'Aves'; ....
        {'o', 8, 3, [0 0 1], [0 0 1]}, 'Testudines'; ....
        {'o', 8, 3, [1 0 1], [0 0 1]}, 'Crocodilia'; ....
        {'o', 8, 3, [1 0 1], [1 0 1]}, 'Avemetatarsalia'; ....
    };
    [Hfig Hleg] = shstat([v1, v2], legend_aves, 'sauropsids', 5); 
    figure(Hfig) 
    figure(Hfig)
    xlabel(xtxt)      
    ylabel(ytxt)
    %saveas(gca,[vtxt, '_aves.png'])
    %saveas(Hleg,['legend_', vtxt, '_aves.png'])

    figure(7)
    legend_mamm = {...
       {'o', 8, 3, [0 0 0], [0 0 0]}, 'Prototheria'; ...  
       {'o', 8, 3, [0 0 1], [0 0 0]}, 'Marsupialia'; ...
       {'o', 8, 3, [0 0 1], [0 0 1]}, 'Xenarthra'; ...
       {'o', 8, 3, [0 0 1], [1 0 1]}, 'Afrotheria'; ....
       {'o', 8, 3, [0 0 1], [1 0 0]}, 'Laurasiatheria'; ....
       {'o', 8, 3, [1 0 1], [1 0 1]}, 'Gliriformes'; ....
       {'o', 8, 3, [1 0 1], [1 0 0]}, 'Scandentia'; ....
       {'o', 8, 3, [1 0 0], [1 0 0]}, 'Dermoptera'; ....
       {'o', 8, 3, [1 0 0], [1 .5 .5]}, 'Primates'; ....
    };
    [Hfig Hleg] = shstat([v1, v2], legend_mamm, 'mammals', 7); 
    figure(Hfig)
    xlabel(xtxt)      
    ylabel(ytxt)
    %saveas(gca,[vtxt, '_mamm.png'])
    %saveas(Hleg,['legend_', vtxt, '_mamm.png'])

